# Generated by Django 5.2.3 on 2025-07-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cnpj', models.BigIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(default='aaa', max_length=45)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(default='user', max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tool', max_length=50)),
                ('description', models.CharField(blank=True, null=True)),
                ('link', models.CharField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(default='test', max_length=100)),
                ('creator', models.CharField(default='test')),
                ('description', models.CharField(blank=True, null=True)),
                ('knowledge', models.CharField(default='black-box', max_length=10)),
                ('aggressivity', models.CharField(default='medium', max_length=10)),
                ('approach', models.CharField(default='covert', max_length=10)),
                ('starting_point', models.CharField(default='external', max_length=10)),
                ('vector', models.CharField(default='network', max_length=40)),
                ('testers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
