# Generated by Django 5.2.4 on 2025-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramonto', '0003_checklist_tests_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
    ]
