# Generated by Django 5.2.4 on 2025-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramonto', '0004_checklistitem_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='clone',
            field=models.BooleanField(default=False),
        ),
    ]
