# Generated by Django 5.2.4 on 2025-09-26 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramonto', '0005_checklist_clone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln', models.CharField(default='vuln', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('vector', models.CharField(default='N/A', max_length=50)),
                ('attack_vector', models.CharField(default='Network', max_length=20)),
                ('attack_complexity', models.CharField(default='Low', max_length=20)),
                ('privileges_required', models.CharField(default='None', max_length=20)),
                ('user_interaction', models.CharField(default='None', max_length=20)),
                ('scope', models.CharField(default='Unchanged', max_length=20)),
                ('confidentiality', models.CharField(default='Low', max_length=20)),
                ('integrity', models.CharField(default='Low', max_length=20)),
                ('availability', models.CharField(default='Low', max_length=20)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='Tramonto.tests')),
                ('tools', models.ManyToManyField(to='Tramonto.tools')),
            ],
        ),
    ]
