# Generated by Django 5.2.4 on 2025-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramonto', '0006_vulnerabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilities',
            name='author',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
