# Generated by Django 5.2.4 on 2025-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tramonto', '0007_vulnerabilities_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilities',
            name='attack_complexity',
            field=models.CharField(default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='attack_vector',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='availability',
            field=models.CharField(default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='confidentiality',
            field=models.CharField(default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='integrity',
            field=models.CharField(default='L', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='privileges_required',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='scope',
            field=models.CharField(default='U', max_length=20),
        ),
        migrations.AlterField(
            model_name='vulnerabilities',
            name='user_interaction',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
